services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: clzlsrnxk15
      MYSQL_DATABASE: dbGeonpil
      MYSQL_USER: geonpil_user
      MYSQL_PASSWORD: clzlsrnxk15
    ports:
      - "3307:3306"
    volumes:
      - ./geonpil-dump.sql:/docker-entrypoint-initdb.d/01-geonpil.sql
      - mysql-data:/var/lib/mysql
    networks:
      - geonpil-net
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -uroot -p$${MYSQL_ROOT_PASSWORD} --silent"]
      interval: 10s
      timeout: 5s
      retries: 20

  elasticsearch:
    image: elasticsearch:8.13.4
    container_name: es-container
    environment:
      node.name: es01
      discovery.type: single-node
      xpack.security.enabled: "true"
      ELASTIC_PASSWORD: "clzlsrnxk15"
      


      xpack.security.http.ssl.enabled: "true"
      xpack.security.http.ssl.certificate: certs/es01/es01.crt
      xpack.security.http.ssl.key: certs/es01/es01.key
      xpack.security.http.ssl.certificate_authorities: certs/ca.crt

      xpack.security.transport.ssl.enabled: "true"
      xpack.security.transport.ssl.verification_mode: certificate
      xpack.security.transport.ssl.certificate: certs/es01/es01.crt
      xpack.security.transport.ssl.key: certs/es01/es01.key
      xpack.security.transport.ssl.certificate_authorities: certs/ca.crt


    volumes:
      - ./certs:/usr/share/elasticsearch/config/certs
      - esdata:/usr/share/elasticsearch/data

    networks:
      - geonpil-net
    # healthcheck는 wget 없는 경우가 많아서, 우선은 빼거나 curl 존재 여부 확인 후 넣는 걸 추천

  geonpil:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: geonpil-container
    depends_on:
      mysql:
        condition: service_healthy
      elasticsearch:
        condition: service_started   # (healthcheck 없으면 started로)
    ports:
      - "18080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/dbGeonpil?serverTimezone=Asia/Seoul
      SPRING_DATASOURCE_USERNAME: geonpil_user
      SPRING_DATASOURCE_PASSWORD: clzlsrnxk15
      SPRING_ELASTICSEARCH_URIS: https://es-container:9200
      ELASTICSEARCH_HOST: https://es-container:9200
      ELASTICSEARCH_USERNAME: elastic
      ELASTICSEARCH_PASSWORD: clzlsrnxk15
      SPRING_ELASTICSEARCH_USERNAME: elastic
      SPRING_ELASTICSEARCH_PASSWORD: clzlsrnxk15
      SPRING_PROFILES_ACTIVE: dev
      SEARCH_SERVICE_BASE_URL: http://search-service:8081

      JAVA_TOOL_OPTIONS: "-Djavax.net.ssl.trustStore=/certs/truststore.jks -Djavax.net.ssl.trustStorePassword=changeit"

    networks:
      - geonpil-net
    volumes:
      - ./certs:/certs:ro

networks:
  geonpil-net:
    name : geonpil-net
    driver: bridge

volumes:
  mysql-data:
  esdata: