version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: clzlsrnxk15
      MYSQL_DATABASE: geonpil
    ports:
      - "3306:3306"
    networks:
      - geonpil-net

  elasticsearch:
    image: elasticsearch:7.17.10
    container_name: es-container
    environment:
      discovery.type: single-node
      xpack.security.enabled: "false"
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - geonpil-net

  geonpil:
    image: geonpil
    container_name: geonpil-container
    depends_on:
      elasticsearch:
        condition: service_healthy
      mysql:
        condition: service_started
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-container:3306/geonpil?serverTimezone=Asia/Seoul
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: clzlsrnxk15
      SPRING_ELASTICSEARCH_URIS: http://es-container:9200
    networks:
      - geonpil-net

networks:
  geonpil-net:
    driver: bridge
